version: '3'
services:
  postgresql:
    image: postgres:11.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: til_dev
    volumes:
     - ${PWD}/db:/var/lib/postgresql/data
