-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (Learning(..), Session(..), User(..))


type Learning
    = Learning


type Session
    = Session


type User
    = User
