-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.User exposing (email, handle, id, learnings)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


email : SelectionSet String Api.Object.User
email =
    Object.selectionForField "String" "email" [] Decode.string


handle : SelectionSet String Api.Object.User
handle =
    Object.selectionForField "String" "handle" [] Decode.string


id : SelectionSet Api.ScalarCodecs.Id Api.Object.User
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


learnings : SelectionSet decodesTo Api.Object.Learning -> SelectionSet (List decodesTo) Api.Object.User
learnings object_ =
    Object.selectionForCompositeField "learnings" [] object_ (identity >> Decode.list)
